@startuml
class MasterPanel{
  Tk window
  nopm()
  pm()
  String _on_enter_pressed()
  String _insert_message()
  String gratitud()
  String abrirdiario()
  String test()
  String sos()
}

class Diario{
  Tk ventana
  volver()
  mostrar_entradas()
  guardar_entrada()
  String _insert_message()
}
class App{
  Tk ventana
  Tk reg
  String username_info
  String password_info
  verificar()
  Registrar_Usuario()
  registrar()
}

class NeuralNet{
  l1
  l2
  l3
  relu
  forward()
}
class chatDatabase{
  LinkedList samples
  LinkedList x_data
  LinkedList y_data
  LinkedList _getitem_()
  LinkedList _len_()
  
}

App*-- MasterPanel
MasterPanel*-- Diario
NeuralNet -- chatDatabase
chatDatabase -- MasterPanel
@enduml
